[package]
name = "pinetime-drivers"
version = "0.1.0"
edition = "2018"

[dependencies]
cortex-m = "0.6"
cortex-m-rtic = "0.6.0-alpha.5"

[dependencies.rtt-target]
version = "0.3"
features = ["cortex-m"]
default-features = false

[dependencies.nrf52832-hal]
version = "0.13"
default-features = false
