[package]
name = "pinetime-graphics"
version = "0.1.0"
edition = "2018"

[dependencies]
embedded-graphics = "0.7"
heapless = "0.7"

[dependencies.err-derive]
version = "0.3"
default-features = false

[dependencies.pinetime-common]
path = "../pinetime-common"
